---
  :global:
    supported_oss:
      modulesync_playground:                     [windows]
      tragiccode-environmentrefresh:             [linux,windows]
      tragiccode-wsusserver:                     [windows]
      tragiccode-googlecloudstorage:             [windows]
      tragiccode-ravendb:                        [windows]
      tragiccode-activedirectory:                [windows]
      tragiccode-dnsserver:                      [windows]
      tragiccode-nservicebusservicecontrol:      [windows]
      tragiccode-nservicebusservicepulse:        [windows]
      tragiccode-vscode:                         [windows]
      tragiccode-octopusdeployserver:            [windows]
      tragiccode-octopusdeploytentacle:          [windows]
      tragiccode-ssh:                            [windows]
      tragiccode-stackify:                       [windows]
      tragiccode-errbot:                         [linux]
      puppetlabs-inifile:                        [linux,windows]
      puppetlabs-accounts:                       [linux]
