---
  :global:
    supported_oss:
      tragiccode-octopusdeploy:            [windows]
      tragiccode-ssh:                      [windows]
      puppetlabs-inifile:                  [linux,windows]
      puppetlabs-accounts:                 [linux]
